61 nueva ventana votacion
ThePhrontistery/py-labar pull request #62
Opened 2023-11-14 10:56 UTC by jjarbona

2023-11-14 10:58 UTC, pchocron commented on app/business/topics/controllers/topic.py
modal_votacion doesn't have the same format as create_vote

2023-11-14 11:04 UTC, pchocron approved these changes

2023-11-14 11:04 UTC, pchocron commented on app/domain/topics/repositories/topic.py
[DUDA] parece que no hay ninguna clase llamando a CreateVoteDto

2023-11-14 11:29 UTC, andsanchez requested changes

2023-11-14 11:29 UTC, andsanchez commented on app/domain/topics/models/topic.py
> +class Vote(BaseUUIDModel, table=True):
Es correcto que todo lo referido esté dentro del directorio "topics", pero aquí al igual que se ha hecho en "repositories", sería mejor tener el fichero "vote.py" en models

2023-11-14 11:29 UTC, andsanchez commented on app/business/topics/controllers/topic.py
> +@router.get("/modal_votacion", response_class=HTMLResponse, name="modal_votacion")
create_vote / modal_votacion / voto (param usado más abajo) 

Cuidado con la mezcla de idiomas. El código debemos escribirlo en inglés.

2023-11-14 11:29 UTC, andsanchez commented on app/business/topics/controllers/topic.py
> +    home_url = user_router.url_path_for("return_home")
Esta linea, es la misma que la línea 183.

¿Se podría extraer una constante en este mismo fichero para HOME_URL?

2023-11-14 11:29 UTC, andsanchez commented on app/business/topics/models/topic.py
> +class CreateVoteDto(BaseModel):
idem al model del repositorio. Pienso que es mejor en "vote.py".

2023-11-15 08:17 UTC, andsanchez commented on app/business/topics/controllers/topic.py
> +    voto: str = Form(...),
voto en español 👀

2023-11-15 08:26 UTC, andsanchez approved these changes

2023-11-15 08:27 UTC, merged